name: docs
on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --only dev

      - name: Build MkDocs
        run: poetry run mkdocs build --strict

      - name: Deploy MkDocs
        if: github.ref == 'refs/heads/main'
        run: poetry run mkdocs gh-deploy --force
