name: Build and upload to PyPI

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    environment: pypi
    permissions:
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build distribution
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
